"""Genera los PDF de los entregables del curso (ruta Report / ReportLab).

Salidas en entregables/:
  1. Khipu_CRM_Informe_Final.pdf      — portada institucional + informe (3-5 págs)
  2. Khipu_CRM_Checklist_Seguridad.pdf — checklist de seguridad (sin portada)
  3. Khipu_CRM_Plan_Pruebas.pdf        — plan y evidencia de pruebas 1-2 págs (sin portada)

Las métricas se leen de ml/artifacts/*.json para que los números del PDF
coincidan siempre con los modelos entrenados.

Uso:  python tools/generar_pdfs.py
"""
import json
import os
import sys
from datetime import date

PDF_SKILL_DIR = os.environ.get(
    "PDF_SKILL_DIR",
    "/Volumes/Mac/Mac Externa/.zcode/cli/plugins/cache/zcode-plugins-official/pdf/0.1.7/skills/pdf",
)
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, KeepTogether, Paragraph, SimpleDocTemplate,
    Spacer, Table, TableStyle,
)

# ━━ Color Palette (auto-generated by pdf.py palette.cascade, seed 7) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#504933')
BORDER        = colors.HexColor('#cfcab8')
ACCENT        = colors.HexColor('#368aa6')
TEXT_PRIMARY  = colors.HexColor('#1c1c1a')
TEXT_MUTED    = colors.HexColor('#78766f')
SEM_SUCCESS   = colors.HexColor('#46875c')

# ── Fuentes del sistema (macOS) ──
SUP = "/System/Library/Fonts/Supplemental"
pdfmetrics.registerFont(TTFont("TNR", f"{SUP}/Times New Roman.ttf"))
pdfmetrics.registerFont(TTFont("TNR-Bold", f"{SUP}/Times New Roman Bold.ttf"))
pdfmetrics.registerFont(TTFont("TNR-Italic", f"{SUP}/Times New Roman Italic.ttf"))
registerFontFamily("TNR", normal="TNR", bold="TNR-Bold", italic="TNR-Italic",
                   boldItalic="TNR-Bold")

Fuentes_docs = {
    "sans": ("TNR", f"{SUP}/Times New Roman.ttf", 0),
    "serif": ("TNR", f"{SUP}/Times New Roman.ttf", 0),
    "latin": ("TNR", f"{SUP}/Times New Roman.ttf", 0),
    "kai": ("TNR", f"{SUP}/Times New Roman.ttf", 0),
}  # font_overrides: rol -> (nombre, ruta, índice)

HOY = date(2026, 9, 20)
AUTORA = "Bayona Valdez, Fany"
CURSO = "Desarrollo de Sistemas Inteligentes II · 2025-2"
INSTITUCION = "Instituto Superior Privado Khipu"

# ── Métricas reales de los modelos ──
with open("ml/artifacts/scoring_metrics.json", encoding="utf-8") as f:
    SC = json.load(f)
with open("ml/artifacts/nlp_metrics.json", encoding="utf-8") as f:
    NLP = json.load(f)
SC_MEJOR = SC["resultados"][SC["modelo_seleccionado"]]
SC_RF = SC["resultados"]["RandomForest"]
MC = SC_MEJOR["matriz_confusion"]  # [[VN, FP], [FN, VP]]

# ── Estilos ──
def st(nombre, **kw):
    base = dict(fontName="TNR", fontSize=10.5, leading=16, alignment=TA_JUSTIFY,
                textColor=TEXT_PRIMARY, spaceAfter=8)
    base.update(kw)
    return ParagraphStyle(nombre, **base)

S = {
    "h1": st("h1", fontSize=17, leading=22, alignment=TA_LEFT, spaceBefore=18,
             spaceAfter=4, fontName="TNR-Bold", textColor=TEXT_PRIMARY),
    "h2": st("h2", fontSize=13.5, leading=18, alignment=TA_LEFT, spaceBefore=14,
             spaceAfter=6, fontName="TNR-Bold", textColor=HEADER_FILL),
    "body": st("body"),
    "bullet": st("bullet", leftIndent=14, spaceAfter=4, alignment=TA_LEFT),
    "quote": st("quote", fontName="TNR-Italic", leftIndent=24, textColor=TEXT_MUTED,
                alignment=TA_LEFT),
    "caption": st("caption", fontSize=8.5, leading=11, textColor=TEXT_MUTED,
                  alignment=TA_CENTER, spaceAfter=10),
    "th": st("th", fontSize=9.5, leading=12, alignment=TA_CENTER, fontName="TNR-Bold",
             textColor=colors.white, spaceAfter=0),
    "td": st("td", fontSize=9.5, leading=12.5, alignment=TA_LEFT, spaceAfter=0),
    "tdc": st("tdc", fontSize=9.5, leading=12.5, alignment=TA_CENTER, spaceAfter=0),
    "stat": st("stat", fontSize=20, leading=24, alignment=TA_CENTER, fontName="TNR-Bold",
               textColor=ACCENT, spaceAfter=0),
    "statlbl": st("statlbl", fontSize=8.5, leading=11, alignment=TA_CENTER,
                  textColor=TEXT_MUTED, spaceAfter=0),
    "code": st("code", fontSize=9, leading=13, alignment=TA_LEFT, fontName="TNR",
               textColor=TEXT_PRIMARY, spaceAfter=0),
    "portada": st("portada", alignment=TA_CENTER, fontSize=11, spaceAfter=2),
}

PAGE_W, PAGE_H = A4
MARGEN = 2.0 * cm
ANCHO = PAGE_W - 2 * MARGEN


def encabezado_pie(titulo_doc):
    def cb(canvas, doc):
        canvas.saveState()
        # Encabezado: título + regla acento
        canvas.setFont("TNR", 7.5)
        canvas.setFillColor(TEXT_MUTED)
        canvas.drawString(MARGEN, PAGE_H - 1.2 * cm, titulo_doc)
        canvas.setStrokeColor(ACCENT)
        canvas.setLineWidth(1.2)
        canvas.line(MARGEN, PAGE_H - 1.35 * cm, PAGE_W - MARGEN, PAGE_H - 1.35 * cm)
        # Pie: autora + página
        canvas.setStrokeColor(BORDER)
        canvas.setLineWidth(0.6)
        canvas.line(MARGEN, 1.35 * cm, PAGE_W - MARGEN, 1.35 * cm)
        canvas.setFont("TNR", 7.5)
        canvas.drawString(MARGEN, 1.0 * cm, f"{AUTORA} · {INSTITUCION}")
        canvas.drawRightString(PAGE_W - MARGEN, 1.0 * cm, f"Pág. {doc.page}")
        canvas.restoreState()
    return cb


def h1(texto):
    return [CondPageBreak(3.2 * cm),
            Paragraph(f"<b>{texto}</b>", S["h1"]),
            HRFlowable(width="100%", thickness=1.1, color=ACCENT,
                       spaceBefore=0, spaceAfter=10)]


def tabla(data, ratios, header=True, stripe=True):
    """Tabla con anchos proporcionales; todo el texto va en Paragraph."""
    anchos = [r * ANCHO for r in ratios]
    t = Table(data, colWidths=anchos, hAlign="CENTER", repeatRows=1 if header else 0)
    estilo = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
    ]
    if header:
        estilo.append(("BACKGROUND", (0, 0), (-1, 0), HEADER_FILL))
    if stripe:
        inicio = 1 if header else 0
        for i in range(inicio, len(data)):
            if (i - inicio) % 2 == 1:
                estilo.append(("BACKGROUND", (0, i), (-1, i), TABLE_STRIPE))
    t.setStyle(TableStyle(estilo))
    return t


def fila_stats(pares):
    """Fila de indicadores destacados (CalloutBox múltiple)."""
    celdas, anchos = [], []
    for valor, etiqueta in pares:
        caja = Table(
            [[Paragraph(f"<b>{valor}</b>", S["stat"])],
             [Paragraph(etiqueta, S["statlbl"])]],
            colWidths=[(ANCHO - 3 * 10) / len(pares)])
        caja.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ("BOX", (0, 0), (-1, -1), 0.8, ACCENT),
            ("TOPPADDING", (0, 0), (-1, 0), 9),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 9),
            ("TOPPADDING", (0, 1), (-1, 1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
        ]))
        celdas.append(caja)
        anchos.append((ANCHO - 3 * 10) / len(pares) + 10)
    fila = Table([celdas], colWidths=anchos, hAlign="CENTER")
    fila.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 0), ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return fila


def bloque_codigo(lineas):
    cuerpo = [[Paragraph(ln.replace(" ", " "), S["code"])] for ln in lineas]
    t = Table(cuerpo, colWidths=[ANCHO * 0.96], hAlign="CENTER")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PAGE_BG),
        ("BOX", (0, 0), (-1, -1), 0.6, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, 0), 8), ("BOTTOMPADDING", (0, -1), (-1, -1), 8),
        ("TOPPADDING", (0, 1), (-1, -1), 1), ("BOTTOMPADDING", (0, 0), (-1, -2), 1),
    ]))
    return t


def P(texto, estilo="body"):
    return Paragraph(texto, S[estilo])


# ════════════════════════════════════════════════════════════════════
# 1. INFORME FINAL (cuerpo; la portada se genera aparte y se fusiona)
# ════════════════════════════════════════════════════════════════════
def cuerpo_informe():
    e = []
    e += h1("1. Resumen ejecutivo")
    e.append(P(
        "Las áreas de Admisión, Convenios e InkaLab del Instituto Superior Privado Khipu pierden "
        "oportunidades de conversión (postulantes, colegios, empresas y aliados) porque su información "
        "de contactos e interacciones está dispersa en hojas de cálculo, WhatsApp, correos y agendas "
        "personales: no existe un mecanismo que priorice automáticamente a los contactos con mayor "
        "probabilidad de conversión ni que alerte sobre seguimientos atrasados."))
    e.append(P(
        "Este proyecto entrega una aplicación web inteligente que resuelve ese problema: un CRM "
        "institucional con <b>scoring predictivo de conversión</b> (machine learning), <b>clasificación "
        "automática de mensajes</b> (NLP, KhipuBot) y <b>alertas de seguimiento</b>, cubierto por "
        "pruebas automatizadas y desplegado en staging. Indicadores clave del sistema:"))
    e.append(Spacer(1, 4))
    e.append(fila_stats([
        (f"{SC_MEJOR['accuracy']:.1%}", "Accuracy del scoring<br/>(Regresión Logística)"),
        (f"{SC_MEJOR['roc_auc']:.3f}", "ROC-AUC del<br/>modelo de scoring"),
        (f"{NLP['accuracy']:.1%}", "Accuracy del<br/>clasificador NLP"),
        ("40", "Pruebas automatizadas<br/>en verde (pytest)"),
    ]))
    e.append(Spacer(1, 14))

    e += h1("2. Arquitectura del sistema")
    e.append(P(
        "Aplicación web de tres capas con el módulo de IA desacoplado lógicamente. La interfaz web "
        "(HTML/CSS/JS + Chart.js) consume una API REST protegida por JWT; el backend FastAPI gestiona "
        "el CRM y orquesta la inferencia; los modelos entrenados viven como artefactos versionados en "
        "Git y se sirven con carga singleton. La base de datos es SQLite en desarrollo y PostgreSQL "
        "en el despliegue (SQLAlchemy abstrae el motor)."))
    e.append(tabla([
        [P("<b>Capa</b>", "th"), P("<b>Tecnología</b>", "th"), P("<b>Responsabilidad</b>", "th")],
        [P("Interfaz web"), P("HTML/CSS/JS vanilla · Chart.js"),
         P("Login, dashboard con embudo, contactos, oportunidades con score, tareas, alertas y KhipuBot")],
        [P("API / Backend"), P("Python · FastAPI · SQLAlchemy"),
         P("25+ endpoints REST documentados en Swagger; JWT con 4 roles; validación Pydantic")],
        [P("Módulo de IA"), P("scikit-learn (TF-IDF, LogReg, RandomForest)"),
         P("Scoring predictivo, clasificación NLP de mensajes y recomendación de próxima acción")],
        [P("Datos"), P("SQLite (dev) · PostgreSQL (staging)"),
         P("Contactos, interacciones, oportunidades, campañas, tareas y usuarios")],
    ], [0.18, 0.30, 0.52]))
    e.append(Paragraph("Tabla 1. Capas de la arquitectura y su responsabilidad.", S["caption"]))

    # El título H1 y el inicio de 3.1 viajan juntos: evita el huérfano al pie.
    e.append(KeepTogether(
        h1("3. Modelo de inteligencia artificial") + [
            Paragraph("<b>3.1 Scoring predictivo de conversión (RF02)</b>", S["h2"]),
            P("Problema de clasificación binaria: dado el comportamiento de una oportunidad, ¿se convertirá "
            f"(matrícula o convenio firmado)? Se entrenó con {SC['filas_dataset']:,} registros sintéticos que "
            f"simulan el histórico centralizado ({SC['distribucion_target']['convertido_1'] / SC['filas_dataset']:.1%} "
            "de conversión), con variables operativas: tipo de contacto, canal de origen, etapa del embudo, "
            "número de interacciones, tiempo promedio de respuesta y días sin interacción."),
        ]))
    e.append(P("<b>Preparación de datos</b> (documentada en ml/train_scoring.py):"))
    e.append(tabla([
        [P("<b>Tarea</b>", "th"), P("<b>Tratamiento aplicado</b>", "th"), P("<b>Cantidad</b>", "th")],
        [P("Limpieza de duplicados"), P("Filas heredadas de hojas de cálculo eliminadas por id de contacto"), P("20", "tdc")],
        [P("Tratamiento de outliers"), P("Tiempos de respuesta > 720 h convertidos a nulos (dato irrecuperable)"), P("46", "tdc")],
        [P("Imputación de nulos"), P("Mediana del tiempo de respuesta (imputer del pipeline)"), P("245", "tdc")],
        [P("Codificación"), P("One-hot para categóricas (tipo, canal, etapa)"), P("—", "tdc")],
        [P("Normalización"), P("Estandarización z-score de variables numéricas"), P("—", "tdc")],
    ], [0.26, 0.58, 0.16]))
    e.append(Paragraph("Tabla 2. Preparación de datos previa al entrenamiento.", S["caption"]))
    e.append(P(
        "Con split estratificado 75/25 (seed fija) se compararon dos candidatos; se seleccionó "
        "<b>Regresión Logística</b> por mayor F1 y ROC-AUC, y por interpretabilidad: sus coeficientes "
        "confirman que respuestas rápidas, más interacciones y etapas avanzadas elevan la probabilidad "
        "de conversión&nbsp;— coherente con el negocio y explicable a los usuarios de Admisión y Convenios."))
    e.append(tabla([
        [P("<b>Modelo</b>", "th"), P("<b>Accuracy</b>", "th"), P("<b>Precision</b>", "th"),
         P("<b>Recall</b>", "th"), P("<b>F1</b>", "th"), P("<b>ROC-AUC</b>", "th")],
        [P("Regresión Logística (seleccionado)"),
         P(f"{SC_MEJOR['accuracy']:.3f}", "tdc"), P(f"{SC_MEJOR['precision']:.3f}", "tdc"),
         P(f"{SC_MEJOR['recall']:.3f}", "tdc"), P(f"<b>{SC_MEJOR['f1']:.3f}</b>", "tdc"),
         P(f"<b>{SC_MEJOR['roc_auc']:.3f}</b>", "tdc")],
        [P("Random Forest (300 árboles)"),
         P(f"{SC_RF['accuracy']:.3f}", "tdc"), P("—", "tdc"), P("—", "tdc"),
         P(f"{SC_RF['f1']:.3f}", "tdc"), P(f"{SC_RF['roc_auc']:.3f}", "tdc")],
    ], [0.30, 0.14, 0.14, 0.14, 0.14, 0.14]))
    e.append(Paragraph(
        f"Tabla 3. Evaluación en test. Matriz de confusión: VN {MC[0][0]}, FP {MC[0][1]}, "
        f"FN {MC[1][0]}, VP {MC[1][1]}.", S["caption"]))

    e.append(Paragraph("<b>3.2 Clasificación NLP — KhipuBot (RF01)</b>", S["h2"]))
    e.append(P(
        f"Clasificador de mensajes entrantes en cinco tipos de contacto (TF-IDF con n-gramas 1-2 + "
        f"Regresión Logística), entrenado con {NLP['ejemplos_entrenamiento']} mensajes simulados que "
        "incluyen ~8% de mensajes ambiguos con etiqueta aleatoria, para reproducir el ruido real de un "
        f"canal multicanal. Resultado en test ({NLP['ejemplos_test']} mensajes): accuracy "
        f"<b>{NLP['accuracy']:.1%}</b> y F1 macro <b>{NLP['f1_macro']:.3f}</b>. La API devuelve la "
        "confianza de la predicción; por debajo de 0.5 la interfaz marca el caso para revisión manual."))
    clases = list(NLP["por_clase"].keys())
    fila_clases = [P("<b>Tipo de contacto</b>", "th")] + [P(f"<b>{c}</b>", "th") for c in clases]
    fila_f1 = [P("<b>F1-score</b>", "td")] + [P(f"{v['f1']:.3f}", "tdc") for v in NLP["por_clase"].values()]
    e.append(tabla([fila_clases, fila_f1], [0.20] + [0.16] * 5))
    e.append(Paragraph("Tabla 4. Métricas del clasificador NLP por tipo de contacto.", S["caption"]))

    e.append(KeepTogether([
        Paragraph("<b>3.3 Recomendación de próxima acción</b>", S["h2"]),
        P("Módulo heurístico que traduce el score en una acción operativa concreta (agendar entrevista "
        "de cierre, llamar y enviar información, reactivar con campaña o evaluar cierre como perdido), "
        "cruzando la probabilidad con los días sin interacción (urgencia). El score se persiste en la "
        "oportunidad y alimenta el dashboard."),
    ]))

    e += h1("4. Pruebas")
    e.append(P(
        "40 pruebas automatizadas con pytest, todas aprobadas en ~1.2 s: 11 unitarias del modelo "
        "(umbrales mínimos de métricas, coherencia de predicciones, clasificación por clase y "
        "rendimiento: 100 scores en menos de 3 s, RNF02) y 29 funcionales de la API (login y JWT, "
        "control de roles, CRUD completo, interacciones, scoring persistido, KhipuBot, tareas, "
        "alertas, dashboard y códigos de error 401/403/404/422). Además, 2 pruebas de regresión "
        "validan que las páginas web carguen sus dependencias JavaScript."))
    e.append(bloque_codigo([
        "$ python -m pytest tests/ -q",
        "40 passed, 2 warnings in 1.15s",
        "",
        "# Las 2 advertencias son deprecations internas de starlette/anyio;",
        "# no afectan los resultados.",
    ]))
    e.append(Spacer(1, 12))

    e += h1("5. Seguridad aplicada")
    for b in [
        "<b>Validación de entradas:</b> esquemas Pydantic en todos los endpoints de escritura, con "
        "dominios restringidos por regex, longitudes máximas y rangos numéricos acotados.",
        "<b>Manejo de errores:</b> mensajes genéricos en login (sin revelar qué campo falló), 404 sin "
        "datos internos y sin stack traces al cliente.",
        "<b>Credenciales:</b> SECRET_KEY y conexión de base de datos por variables de entorno; .env "
        "excluido del repositorio; contraseñas con PBKDF2-HMAC-SHA256 (120 000 iteraciones) y "
        "comparación resistente a timing attacks.",
        "<b>Control de acceso (RNF01):</b> JWT con expiración y jerarquía de roles "
        "lector < admisión < gestor < admin, verificada por pruebas (403).",
        "<b>Frontend:</b> escapado de todo contenido dinámico contra XSS y cierre de sesión que "
        "elimina el token.",
    ]:
        e.append(P(f"• {b}", "bullet"))
    e.append(P("El detalle completo, con la verificación de cada práctica, está en el checklist de "
               "seguridad (documento adjunto).", "body"))

    e += h1("6. Despliegue")
    e.append(P(
        "El sistema se despliega como contenedor Docker (Dockerfile + docker-compose con PostgreSQL) "
        "y en Render mediante el blueprint render.yaml (web service + PostgreSQL gestionado, healthcheck "
        "en /health). La documentación de la API queda disponible en /docs (Swagger autogenerado) en "
        "cualquier entorno. URL de staging: https://khipu-crm.onrender.com."))

    e += h1("7. Conclusiones")
    for b in [
        "Se cumplió el objetivo: un CRM web funcional cuyo diferencial de IA no solo almacena datos, "
        "sino que prioriza contactos y sugiere acciones concretas de seguimiento.",
        f"El modelo de scoring alcanza {SC_MEJOR['roc_auc']:.3f} de ROC-AUC con seis variables "
        "operativas sencillas, lo que lo hace explicable y fácil de adoptar.",
        "El cuello de botella identificado es la calidad del dato: centralizar las interacciones es "
        "condición para que el scoring aporte valor (como anticipó la fase de preparación de datos).",
        "Trabajo futuro: reentrenar periódicamente con datos reales, integrar WhatsApp Business API "
        "para KhipuBot (Zapier o n8n como puente), y conectar con la cartera DTA (Khipu DataBoard, "
        "Khipu ID).",
    ]:
        e.append(P(f"• {b}", "bullet"))
    return e


# ════════════════════════════════════════════════════════════════════
# 2. CHECKLIST DE SEGURIDAD (sin portada: documento funcional)
# ════════════════════════════════════════════════════════════════════
def cuerpo_checklist():
    e = []
    e.append(Paragraph("<b>Checklist de seguridad básica</b>", S["h1"]))
    e.append(HRFlowable(width="100%", thickness=1.1, color=ACCENT, spaceAfter=6))
    e.append(P(
        f"{AUTORA} · {CURSO} · {INSTITUCION} · {HOY.strftime('%d/%m/%Y')}", "quote"))
    e.append(P(
        "Entregable N.° 3 de las bases del proyecto final. Estado de cada práctica de seguridad "
        "básica exigida: validación de inputs, manejo de errores, credenciales fuera del código "
        "fuente y control de acceso. La columna de verificación indica la prueba automatizada "
        "(pytest) o el archivo que la respalda."))

    def seccion(titulo, filas):
        e.append(Paragraph(f"<b>{titulo}</b>", S["h2"]))
        data = [[P("<b>Práctica</b>", "th"), P("<b>Implementación</b>", "th"),
                 P("<b>Verificación</b>", "th"), P("<b>Cumple</b>", "th")]]
        for practica, impl, verif in filas:
            data.append([P(practica), P(impl), P(verif, "tdc"),
                         P("<b>Sí</b>", "tdc")])
        e.append(tabla(data, [0.24, 0.42, 0.24, 0.10]))
        e.append(Spacer(1, 6))

    seccion("Validación de inputs", [
        ("Esquemas estrictos", "Pydantic en todos los endpoints de escritura (app/schemas.py)", "F14/F15: 422"),
        ("Dominios cerrados", "tipo/canal/etapa/estado restringidos por regex", "tests API"),
        ("Longitudes y rangos", "max_length en textos; montos ≥ 0; horas ≤ 1 año", "tests API"),
        ("Correo válido", "EmailStr con email-validator", "F15: 422"),
        ("Paginación acotada", "límite ≤ 200 por consulta", "Query(le=200)"),
    ])
    seccion("Manejo de errores", [
        ("Sin stack traces", "FastAPI devuelve JSON {detail} controlado", "revisión API"),
        ("Login genérico", "\"Credenciales incorrectas\" (no revela el campo fallido)", "F02/F03: 401"),
        ("404 limpios", "recursos inexistentes sin datos internos", "F13: 404"),
        ("Frontend estable", "try/catch + notificación en cada llamada", "revisión UI"),
    ])
    seccion("Credenciales y secretos", [
        ("Sin secretos en código", "SECRET_KEY/DATABASE_URL por variables de entorno", "app/config.py"),
        ("Plantilla sin secretos", ".env.example documentado", "repositorio"),
        (".env ignorado", "excluido del control de versiones", ".gitignore"),
        ("Hash de contraseñas", "PBKDF2-HMAC-SHA256, 120 000 iteraciones + salt", "app/auth.py"),
        ("Timing-safe", "comparación con hmac.compare_digest", "app/auth.py"),
        ("Tokens con expiración", "JWT HS256, 8 h configurable", "RNF01"),
    ])
    seccion("Control de acceso (RNF01)", [
        ("API protegida", "todas las rutas exigen token (salvo login y health)", "F05: 401"),
        ("Jerarquía de roles", "lector < admisión < gestor < admin", "F07/F08"),
        ("Escritura restringida", "crear/editar exige rol admisión o superior", "F07: 403"),
        ("Borrado solo admin", "eliminación de contactos exclusiva del administrador", "F16: 403/204"),
    ])
    seccion("Frontend", [
        ("Token en cliente", "localStorage con logout que lo elimina", "static/js/api.js"),
        ("Expiración manejada", "respuesta 401 redirige al login", "interceptor api.js"),
        ("Protección XSS", "todo contenido dinámico se escapa", "views.js esc()"),
    ])

    e.append(Paragraph("<b>Pendientes para producción real (fuera del alcance académico)</b>", S["h2"]))
    e.append(P(
        "• HTTPS terminado por la plataforma (Render/Docker).<br/>"
        "• Rate limiting en /auth/login (p. ej. slowapi) si el sistema se expone de forma permanente.<br/>"
        "• Rotación programada de SECRET_KEY y cifrado en reposo del disco gestionado de la base de datos.",
        "bullet"))
    return e


# ════════════════════════════════════════════════════════════════════
# 3. PLAN Y EVIDENCIA DE PRUEBAS (1-2 páginas, sin portada)
# ════════════════════════════════════════════════════════════════════
def cuerpo_pruebas():
    e = []
    e.append(Paragraph("<b>Plan y evidencia de pruebas</b>", S["h1"]))
    e.append(HRFlowable(width="100%", thickness=1.1, color=ACCENT, spaceAfter=6))
    e.append(P(f"{AUTORA} — {CURSO}<br/>{INSTITUCION}, {HOY.strftime('%d/%m/%Y')}", "quote"))

    e.append(Paragraph("<b>Estrategia</b>", S["h2"]))
    e.append(tabla([
        [P("<b>Nivel</b>", "th"), P("<b>Alcance</b>", "th"), P("<b>Herramienta</b>", "th"), P("<b>Archivo</b>", "th")],
        [P("Unitarias"), P("Modelo de IA: métricas mínimas, coherencia de predicciones, NLP por clase, rendimiento"),
         P("pytest"), P("tests/test_modelo_ia.py")],
        [P("Funcionales"), P("API completa: auth, roles, CRUD, scoring, alertas, dashboard, páginas web"),
         P("pytest + TestClient"), P("tests/test_api_*.py")],
    ], [0.15, 0.47, 0.18, 0.20]))
    e.append(P(
        "La base de pruebas es un SQLite aparte que se recrea por sesión; el cliente levanta la "
        "aplicación completa (lifespan incluido), por lo que cada corrida es determinista."))

    e.append(Paragraph("<b>Casos unitarios — modelo de IA (11)</b>", S["h2"]))
    e.append(tabla([
        [P("<b>Grupo</b>", "th"), P("<b>Casos</b>", "th"), P("<b>Criterio de aprobación</b>", "th")],
        [P("Artefactos y métricas"), P("U01–U03"), P("modelos presentes; scoring: acc ≥ 0.75, F1 ≥ 0.70, AUC ≥ 0.80; NLP: acc y F1 ≥ 0.85")],
        [P("Coherencia del scoring"), P("U04–U06"), P("respuesta rápida + etapa avanzada → mayor probabilidad; predicciones en [0,1]; recomendaciones coherentes")],
        [P("Clasificación NLP"), P("U07–U10"), P("postulante, empresa, colegio y egresado correctamente clasificados")],
        [P("Rendimiento (RNF02)"), P("U11"), P("100 scores en < 3 s (carga singleton del modelo)")],
    ], [0.26, 0.14, 0.60]))

    e.append(Paragraph("<b>Casos funcionales — API e interfaz (29)</b>", S["h2"]))
    e.append(tabla([
        [P("<b>Grupo</b>", "th"), P("<b>Casos</b>", "th"), P("<b>Criterio de aprobación</b>", "th")],
        [P("Autenticación"), P("F01–F06"), P("login válido emite token; password/usuario incorrectos y token inválido → 401; validación → 422")],
        [P("Roles"), P("F07–F09"), P("lector no crea (403) pero consulta (200); admisión crea (201)")],
        [P("Contactos e interacciones"), P("F10–F17"), P("CRUD, búsqueda, filtros, validaciones 422, borrado solo admin, historial")],
        [P("Oportunidades e IA"), P("F18–F22"), P("score persistido en [0,1] con recomendación; cambio de etapa; /ml/score directo; KhipuBot clasifica y crea contacto")],
        [P("Tareas, alertas, dashboard"), P("F23–F27"), P("tarea pendiente → hecha; alertas de seguimiento; embudo completo; campañas; healthcheck")],
        [P("Interfaz web"), P("2 de regresión"), P("login y panel cargan todas sus dependencias JavaScript")],
    ], [0.26, 0.14, 0.60]))

    e.append(Paragraph("<b>Evidencia de ejecución</b>", S["h2"]))
    e.append(bloque_codigo([
        "$ source .venv/bin/activate",
        "$ python -m pytest tests/ -q",
        "40 passed, 2 warnings in 1.15s",
    ]))
    e.append(P(
        "Reproducción: clonar el repositorio, crear el entorno virtual, instalar requirements.txt y "
        "ejecutar pytest (README, sección \"Ejecutar las pruebas\"). El detalle caso por caso está en "
        "docs/04-plan-de-pruebas.md del repositorio."))
    return e


# ════════════════════════════════════════════════════════════════════
# Construcción
# ════════════════════════════════════════════════════════════════════
def construir(nombre, story, titulo):
    doc = SimpleDocTemplate(
        os.path.join("entregables", nombre), pagesize=A4,
        leftMargin=MARGEN, rightMargin=MARGEN, topMargin=2.1 * cm, bottomMargin=1.9 * cm,
        title=titulo, author=AUTORA, creator=AUTORA,
        subject=f"{CURSO} — Proyecto final integrador",
    )
    doc.build(story, onFirstPage=encabezado_pie(titulo), onLaterPages=encabezado_pie(titulo))


def portada_y_fusion(cuerpo_pdf, salida_pdf, titulo):
    from cover_render import render_cover
    from pypdf import PdfReader, PdfWriter

    contenido = {
        "institution": "I.S.P. KHIPU",
        "doc_type": "INFORME TÉCNICO FINAL",
        "title": "Khipu CRM Académico-Comercial:<br/>seguimiento inteligente de postulantes, alumnos, aliados y proyectos",
        "fields": [
            ["Documento", "Proyecto final integrador"],
            ["Alumna", AUTORA],
            ["Curso", "Desarrollo de Sistemas Inteligentes II (2025-2)"],
            ["Docente", "Poma Enrríquez, Genaro Raúl"],
            ["Ciclo", "2025-2 · Sesión de cierre"],
        ],
        "date": "Cusco, Perú · setiembre de 2026",
    }

    paleta = {"primary": "#368aa6", "text": "#1c1c1a", "muted": "#78766f", "bg": "#ffffff"}
    render_cover("09", contenido, "entregables/_portada.pdf", palette=paleta,
                 font_overrides=Fuentes_docs)

    writer = PdfWriter()
    writer.add_page(PdfReader("entregables/_portada.pdf").pages[0])
    for page in PdfReader(cuerpo_pdf).pages:
        writer.add_page(page)
    writer.add_metadata({"/Title": titulo, "/Author": AUTORA, "/Creator": AUTORA,
                         "/Subject": f"{CURSO} — Proyecto final integrador"})
    with open(salida_pdf, "wb") as f:
        writer.write(f)
    os.remove("entregables/_portada.pdf")
    os.remove(cuerpo_pdf)


if __name__ == "__main__":
    os.makedirs("entregables", exist_ok=True)

    construir("_informe_cuerpo.pdf", cuerpo_informe(),
              "Khipu CRM Académico-Comercial — Informe técnico final")
    portada_y_fusion("entregables/_informe_cuerpo.pdf",
                     "entregables/Khipu_CRM_Informe_Final.pdf",
                     "Khipu CRM Académico-Comercial — Informe técnico final")

    construir("Khipu_CRM_Checklist_Seguridad.pdf", cuerpo_checklist(),
              "Khipu CRM — Checklist de seguridad básica")
    construir("Khipu_CRM_Plan_Pruebas.pdf", cuerpo_pruebas(),
              "Khipu CRM — Plan y evidencia de pruebas")

    print("PDFs generados en entregables/")
